name: Image Classification

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scan:
    name: Run security scans
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - run: pip install bandit
      - run: bandit -r .
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run OWASP Dependency-Check
        run: |
          docker run --rm \
            --volume $(pwd):/src \
            owasp/dependency-check \
            --scan /src \
            --format "ALL" \
            --out /src/dependency-check-report
