name: Image Classification Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scan:
    name: Run security scans
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure entire history is fetched for accurate scans

      # Step 2: Run gitleaks to scan for sensitive data in the repository
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Required for accessing repository

      # Step 3: Setup Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11  # Specify Python version needed for your project

      # Step 4: Install and run Bandit for Python code security analysis
      - name: Install and run Bandit
        run: |
          pip install bandit
          bandit -r .

      # Step 5: Install and run pip-audit to check vulnerabilities in Python dependencies
      - name: Install and run pip-audit
        run: |
          pip install pip-audit
          pip-audit -r requirements.txt

  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      # Step 6: Checkout the repository
      - uses: actions/checkout@v4
      
      - name: Build Docker Image
        run: docker build -f Dockerfile -t nithinpj09/classifier:v1.0 .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: 'nithinpj09/classifier:v1.0'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
